# Generated by Django 3.2 on 2021-05-16 01:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('thanks', models.TextField(max_length=200, verbose_name='今日の感謝')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 16, 1, 36, 34, 359066, tzinfo=utc), verbose_name='作成日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
