# Generated by Django 3.1.5 on 2021-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sleep_time',
            field=models.TimeField(null=True),
        ),
    ]
