# Generated by Django 3.1.5 on 2021-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0002_list_sleep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.FloatField(null=True),
        ),
    ]
