# Generated by Django 3.2.15 on 2022-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0002_auto_20211228_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.FloatField(blank=True, null=True, verbose_name='sleep_time'),
        ),
    ]
