# Generated by Django 3.1.5 on 2021-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0003_auto_20210207_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.TimeField(null=True),
        ),
    ]
