# Generated by Django 3.1.5 on 2021-02-09 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0004_auto_20210207_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sleep_quality',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='睡眠の質'),
        ),
        migrations.AddField(
            model_name='list',
            name='staff_comment',
            field=models.TextField(max_length=200, null=True, verbose_name='スタッフコメント'),
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='list',
            name='go_to_bed',
            field=models.TimeField(verbose_name='就寝時間'),
        ),
        migrations.AlterField(
            model_name='list',
            name='short_comment',
            field=models.TextField(max_length=200, verbose_name='感想'),
        ),
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.TimeField(null=True, verbose_name='睡眠時間'),
        ),
        migrations.AlterField(
            model_name='list',
            name='wakeup',
            field=models.TimeField(verbose_name='起床時間'),
        ),
    ]
