# Generated by Django 3.1.5 on 2021-02-11 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0006_auto_20210210_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='list',
            name='go_to_bed',
            field=models.DateTimeField(verbose_name='go_to_bed'),
        ),
        migrations.AlterField(
            model_name='list',
            name='short_comment',
            field=models.TextField(max_length=200, verbose_name='short_comment'),
        ),
        migrations.AlterField(
            model_name='list',
            name='sleep_quality',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='sleep_quality'),
        ),
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.TimeField(null=True, verbose_name='sleep_time'),
        ),
        migrations.AlterField(
            model_name='list',
            name='staff_comment',
            field=models.TextField(max_length=200, null=True, verbose_name='staff_comment'),
        ),
        migrations.AlterField(
            model_name='list',
            name='wakeup',
            field=models.DateTimeField(verbose_name='wakeup'),
        ),
    ]
