# Generated by Django 3.1.5 on 2021-02-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0007_auto_20210211_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='staff_comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='staff_comment'),
        ),
    ]
