# Generated by Django 3.1.5 on 2021-02-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0008_auto_20210211_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.TimeField(blank=True, null=True, verbose_name='sleep_time'),
        ),
    ]
