# Generated by Django 3.1.5 on 2021-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0010_auto_20210211_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='go_to_bed',
            field=models.DateTimeField(verbose_name='go_to_bed'),
        ),
        migrations.AlterField(
            model_name='list',
            name='wakeup',
            field=models.DateTimeField(verbose_name='wakeup'),
        ),
    ]
