# Generated by Django 3.1.5 on 2021-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0012_auto_20210214_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(unique=True, verbose_name='date'),
        ),
    ]
