# Generated by Django 3.1.5 on 2021-02-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0013_auto_20210214_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSpreadWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sleep_time'),
        ),
    ]
