# Generated by Django 3.1.5 on 2021-02-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthapp', '0014_auto_20210217_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sleep_time',
            field=models.TimeField(blank=True, null=True, verbose_name='sleep_time'),
        ),
    ]
