# Generated by Django 3.2 on 2021-05-14 23:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('go_to_bed', models.DateTimeField(verbose_name='go_to_bed')),
                ('wakeup', models.DateTimeField(verbose_name='wakeup')),
                ('short_comment', models.TextField(max_length=200, verbose_name='short_comment')),
                ('sleep_time', models.TimeField(blank=True, null=True, verbose_name='sleep_time')),
                ('sleep_quality', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='sleep_quality')),
                ('staff_comment', models.TextField(blank=True, max_length=200, verbose_name='staff_comment')),
                ('atmosphere', models.FloatField(null=True, verbose_name='atmosphere')),
                ('min_temp', models.FloatField(null=True, verbose_name='min_temperature')),
                ('max_temp', models.FloatField(null=True, verbose_name='max_temperature')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
